#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if ! type -p dotnet > /dev/null; then
    echo "Could not find 'dotnet' launcher..." 1>&2
    exit 1
fi

exec dotnet "$DIR/aspnet-build.dll"